Repository FuelLabs/fuel-tx, pull requests merged in 2022-02, with the labels that each got.

#75 Storage Slot Initialization
  src/consts.rs
  src/lib.rs
  src/transaction.rs
  src/transaction/id.rs
  src/transaction/offset.rs
  src/transaction/txio.rs
  src/transaction/types.rs
  src/transaction/types/storage.rs
  src/transaction/validation.rs
  src/transaction/validation/error.rs
  tests/bytes.rs
  tests/offset_cases/factory.rs
  tests/valid_cases/transaction.rs
Labels: enhancement, breaking

#81 feat: improve error logging for invalid identifiers
  src/receipt/receipt_repr.rs
  src/transaction.rs
  src/transaction/types/input.rs
  src/transaction/types/output.rs
Labels: enhancement

#57 Add `secp256k1` signature for `Input::Coin`
  .github/workflows/ci.yml
  Cargo.toml
  src/builder.rs
  src/consts.rs
  src/crypto.rs
  src/lib.rs
  src/receipt.rs
  src/receipt/receipt_repr.rs
  src/receipt/receipt_std.rs
  src/transaction.rs
  src/transaction/id.rs
  src/transaction/internals.rs
  src/transaction/metadata.rs
  src/transaction/offset.rs
  src/transaction/repr.rs
  src/transaction/txio.rs
  src/transaction/types/input.rs
  src/transaction/types/output.rs
  src/transaction/types/storage.rs
  src/transaction/types/utxo_id.rs
  src/transaction/types/witness.rs
  src/transaction/validation.rs
  src/transaction/validation/error.rs
  test-helpers/Cargo.toml
  test-helpers/src/lib.rs
  tests/bytes.rs
  tests/offset.rs
  tests/offset_cases/mod.rs
  tests/valid_cases/input.rs
  tests/valid_cases/output.rs
  tests/valid_cases/transaction.rs
Labels: breaking
