Repository FuelLabs/fuel-tx, pull requests merged in 2022-06, with the labels that each got.

#136 Add `Transaction::receipts_root_offset`
  src/transaction/offset.rs
  tests/bytes.rs
  tests/offset.rs
Labels: enhancement

#140 Bump to v0.12.2
  Cargo.toml
Labels: documentation

#141 Add gas price factor consensus parameter
  src/transaction.rs
  src/transaction/consensus_parameters.rs
  src/transaction/id.rs
  tests/bytes.rs
  tests/valid_cases/transaction.rs
Labels: enhancement

#147 Remove static_contracts
  src/builder.rs
  src/consts.rs
  src/transaction.rs
  src/transaction/consensus_parameters.rs
  src/transaction/id.rs
  src/transaction/offset.rs
  src/transaction/txio.rs
  src/transaction/validation.rs
  src/transaction/validation/error.rs
  test-helpers/src/lib.rs
  tests/bytes.rs
  tests/valid_cases/transaction.rs
Labels: breaking
