Repository FuelLabs/fuel-tx, pull requests merged in 2022-05, with the labels that each got.

#111 Split `Input::coin` into predicate and signed
  src/builder.rs
  src/transaction.rs
  src/transaction/id.rs
  src/transaction/offset.rs
  src/transaction/types/input.rs
  src/transaction/types/witness.rs
  src/transaction/validation.rs
  src/transaction/validation/error.rs
  test-helpers/Cargo.toml
  test-helpers/src/lib.rs
  tests/bytes.rs
  tests/valid_cases/input.rs
  tests/valid_cases/output.rs
  tests/valid_cases/transaction.rs
Labels: enhancement, breaking

#122 Update serde features to new schema
  .github/workflows/ci.yml
  Cargo.toml
  src/receipt.rs
  src/receipt/script_result.rs
  src/transaction.rs
  src/transaction/metadata.rs
  src/transaction/types/input.rs
  src/transaction/types/output.rs
  src/transaction/types/storage.rs
  src/transaction/types/utxo_id.rs
  src/transaction/types/witness.rs
  src/transaction/validation/error.rs
  test-helpers/Cargo.toml
  tests/bytes.rs
Labels: breaking

#123 Add bytecode length to tx
  src/builder.rs
  src/transaction.rs
  src/transaction/internals.rs
  src/transaction/txio.rs
  src/transaction/validation.rs
  tests/valid_cases/transaction.rs
Labels: bug

#117 Split `Input::coin` into predicate and signed (#111)
  src/builder.rs
  src/transaction.rs
  src/transaction/id.rs
  src/transaction/internals.rs
  src/transaction/offset.rs
  src/transaction/types/input.rs
  src/transaction/types/utxo_id.rs
  src/transaction/types/witness.rs
  src/transaction/validation.rs
  src/transaction/validation/error.rs
  test-helpers/Cargo.toml
  test-helpers/src/lib.rs
  tests/bytes.rs
  tests/valid_cases/input.rs
  tests/valid_cases/output.rs
  tests/valid_cases/transaction.rs
Labels: breaking

#130 Refactor most constants as configurable parameters
  src/consts.rs
  src/lib.rs
  src/transaction.rs
  src/transaction/consensus_parameters.rs
  src/transaction/id.rs
  src/transaction/validation.rs
  tests/bytes.rs
  tests/valid_cases/input.rs
  tests/valid_cases/transaction.rs
Labels: enhancement

#128 Update contract initial state root to SMT
  Cargo.toml
  src/contract.rs
  src/lib.rs
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-1.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-10.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-100.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-2.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-3.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-4.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-5.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-6.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-7.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-8.snap
  src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-9.snap
  src/snapshots/fuel_tx__contract__tests__default_state_root_snapshot.snap
  src/snapshots/fuel_tx__contract__tests__state_root_snapshot@state-root-0.snap
  src/snapshots/fuel_tx__contract__tests__state_root_snapshot@state-root-1.snap
  src/transaction.rs
  src/transaction/metadata.rs
  src/transaction/offset.rs
  src/transaction/types/input.rs
  src/transaction/validation.rs
  tests/bytes.rs
  tests/valid_cases/input.rs
Labels: enhancement
